### ISSUE TITLE
render spree partials in comfy

### ISSUE THREAD

**Issue by connecticus** [hazg/spree_comfy#1]
I try to render spree partials in comfy layout via {{ cms:partial:path/to/partial }} but have problems with methods. 

Is it possible a closer integration comfy+spree?

I understand that add any decorators is need...

Thank you for your work!

Kate.

**Comment by hazg** [comment]
Hmm, more info please...
spree and comfy versions, code example

**Comment by hazg** [comment]
i can't repeat a problem
need more info: what partial, debug log...

**Comment by connecticus** [comment]
thanks for the reply,

when I try to execute any partials containing

<%= link_to truncate(product.name, :length => 50), product, :class => 'product-name', :title => product.name %>

I am

get the error:

undefined method `product_path' 

Completed 500 Internal Server Error in 396ms

ActionView::Template::Error (undefined method `product_path' for #<#<Class:0x007fe278a041c0>:0x007fe279e47998>):
    21: </figure>
    22: 
    23: 
    24: <%= link_to truncate(product.name, :length => 50), product, :class => 'product-name', :title => product.name %>
  app/helpers/spree/base_helper.rb:161:in`method_missing'
  app/views/spree/shared/_fancy_product.html.erb:24:in `_3a7f93737a6043cb63f10bad2aa471e9'
  app/views/spree/shared/_hits.html.erb:39:in`block in _4c66e115f0ade9c23da3d87a23c25ebb'
  app/views/spree/shared/_hits.html.erb:38:in `each'
  app/views/spree/shared/_hits.html.erb:38:in`_4c66e115f0ade9c23da3d87a23c25ebb'

**Comment by hazg** [comment]
ok. try now.

9d07c9c7cc792e09a068ff1fd40eb680595bc32d

**Comment by connecticus** [comment]
Hi, Alex,

I use your solution - all great. In difficult cases (for ex. when need render any spree-related partial in comfy), I use something like - :locals => { :products => @products, :taxon => @taxon }

Sorry, did not answer immediately. 

Thank you so much!

Kate.

**Comment by hazg** [comment]
Great!
Feel free to post another issue.

**Comment by connecticus** [comment]
This is a revolutionary solution for Spree. It is more flexible and not so ugly like alchemy+spree (:sorry).
Thank you for good product, Alex.

**Comment by hazg** [comment]
Thanks to https://github.com/comfy/comfortable-mexican-sofa
Not me.
But sounds good, thank you ))
