### ISSUE TITLE
Why have a comfy_snippet method?

### ISSUE THREAD

**Issue by ryanburnette** [hazg/spree_comfy#3]
I'm just curious why the `comfy_snippet` method isn't just `cms_snippet_content` or `cms_snippet_render`. Right now I have some partials that get used in both Comfy and Spree. It's ugly, but to get it to work I have a lot of instances of this:

``` html
<%= cms_snippet_render(:foo) %>
<%= comfy_snippet(:foo) %>
```

Would it be difficult for the Gem to just make methods like `cms_snippet_content` and `cms_snippet_render` when views are being rendered by Spree?

**Comment by hazg** [comment]
comfy_snippet - just a sugar without need to use html_safe.
By now you can use cms_snippet_content and cms_snippet_render in partial and views when views are rendered by spree.

In future it can be other helpers, and prefixes like "spree_some_func" and "comfy_some_func" looks good for me. Is't it?

**Comment by ryanburnette** [comment]
I'm using Spree 3, CMS 1.12.7 and the latest spree_comfy, but the `cms_snippet_content` and `cms_snippet_render` methods don't return anything from Spree. Is it because there is no `@cms_site` defined in that context?

**Comment by hazg** [comment]
But comfy_snippet return valid data?


I don't test it on spree 3. readme and gemspec fixed. 3-0-stable branch added.

I'll look for spree 3.0 in my future projects, by now i think that spree 3.0 is very unstable for production. For me. Sorry.

**Comment by hazg** [comment]
Closed. For spree 3.\* use 3-0-stable branch.
